import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";
import Header from "@/components/Header";
import AdsLine from "@/components/AdsLine";
import { getServerSession } from "next-auth";
import { options } from "@/lib/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GREENMIND",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <AdsLine />
          <Header />
          <div className="min-h-[calc(100vh-100px)]">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
